language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: L7+qeuiqoknMYtCzCudxqCGq/yLwZMRWKV2WHl+XoKOe+t9f0TnakzSiXNHyAT0V8ifZi9JBUlAJtyJQRGj+XbPto3oR6rhLJORG63kcPj1+NgTRXiw89sctBi3f3GqZy9WTd7Wdl+CQ13o9yqcqvdzrmkXe+4heUvJyjkLyO2CmhSYmK0WkFxTtEaogqNQtIQgEPqQshWZNCKH6XfrwcL5uHoHsroabNAM9jCVpEoQe6HSK6ga8kxF5bdnk81pHzD1F5bpjSqMOoNWfmWXfm/kroiWfIlu56bspCLPESXuOolWg5ZMHz5xC+ogab1kajxxAHjzz4EM1aaPCclNuEqWtQA9t1w3txYq710qk3G4Dv0+wH7NRUswDrNTQlcYNSzr1iFo3lKcNVfhJRcCiDDVCq+6VlWbONYG0sy1L4aoJFDZRMVNmfkSOWsIUYpoNezj+0tGDoIoW1uJg19gHR3WYXEsWBmzz6H+/FpeXxnH0WmbnwtEgdWYp9HjvSdrBpnDD9D0eiQMdQxxF54/DobtZmUNrknNaAnq3Glz41KeOhR0ZHpoPmP7YJV4Qj0dTzb7YTyFLc+vBavOCx1mVVli4w6fQv2PhkeFvZfc7CYZ0vyiNi0LtcE5hSBJREuTU30IuK3556aTyrtOou/yGmVjSNGusemlL8REn3d/HZes=
  app: test-devops-do-zero
  edge: true
