language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: bykHXYg5qreTORAulgo6ST9cljh2BEjfcZIrlg+F5/GhOEpru/VH9RJC8lHPQBqIvqIXy5vZrVGa9CS3HUJqELnQZDplS3p2onriKZXqTasRbtH0WswKSx1wGNB4qKg6Z9K4Cb1YNXjUfXmAhfexGrFTuhXsR5/glNIu0lLcvo92tUWDfW4m8LMWXv6lwzizNMvlqKhkWhl60Y3ZYVwiY54c1OaFd8rommebSReoAnJKYKCnGK8CRV6fu8fzgtoBQqxeYkWYzMQq9YkH2BFx+YvpuVvdqBk4R9dl2EhE3vhpij6P8rJa6mj0Z1zLZ8u/gCCXxNTdZn4Tze1ml1Vb97E2sz+BpJhLwzc/rtgEpov99TLdTQIIm8/LYc0iB2BGxfAItlXy8ieMDEJ0hkz+jMBECGjbxJHIE2Umh2+JorRKMQ4dTYmigeA+AXfFndTuHTCTIvg4dKmIc6tH9nr/wY+w1kIAjHPu4dcdK35hIRAqv90RsuNnznX/xCuhwEcooo8qUuldBkGYcHb03Jtwi1LX80m3J+hvHoeq2onzDNYyyGAF3ju/834r396pisQ06V1oYseYPT756gDdueT2JEOjuDAF3NsB387bggBMMqlvg16W+ipHfwfiPNPCqrIisted+mz2KodWAe0X0hZbNaytTm9vhIK0MQIFK6E9E1M=
  app: test-devops-do-zero
  edge: true
cls